# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:title.html 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: "rouge"

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : OpenTechSchool
tagline: "organizing tech workshops. Hands-on, awesome, and free."
description: "OpenTechSchool is a movement aiming to offer free tech education. Our events are open to technology enthusiasts of all genders, backgrounds, and experience levels, willing to coach or learn in a friendly environment. Our learning material is shared and collectively improved by the online community and anyone is welcome to use it to organize new OTS chapters anywhere in the world."
author :
  name : Aleks
  email : aleks@opentechschool.org
  github : OpenTechSchool
  twitter : opentechschool 
  gplus: 110892884103962638885  

publisher: ## OpenTechSchool Page
  gplus: 114834784518588736271

authors:
  aleks: 
    name: Aleks
    gplus: 110892884103962638885
    email: aleks at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/aleks.jpg
    about: is the community manager of Co.Up, the coworking space where it all began. At the OpenTechSchool she helps with organising events and as a magician with words is in charge of copy-editing.
  amelie:
    name: "Amélie Anglade"
    gplus: 113881124006632726148
    email: amelie at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/amelie.jpg
    about: is Software Engineer at frestyl and Tech Ambassador of the Berlin Geekettes. For the OpenTechSchool she does public appearances, organises workshops (best known for python) and works at the long- and short-term strategies, such as the launch of Hackership.
  angus:
    name: "Angus Gratton"
    email: angus at opentechschool dot org
    image: https://www.opentechschool.org/images/team/angus.jpg
    about: Angus is a "full stack" software developer who has worked on a variety of software, from desktop and web applications to scientific real time control systems. Co-organiser of OpenTechSchool Melbourne.
  bea:
    name: Beatrice Martini
    gplus: 117054742827125727334
    email: beatrice @ OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/beatrice.jpg
    about: is Event Project Manager for the Open Knowledge Foundation. She contributes to the OpenTechSchool by in organising events and workshops, takes care about CI and public appereances.
  ben:
    name: "Benjamin Kampmann"
    gplus: 104898591568170720911
    email: ben at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/ben.jpg
    about: is freelance Software Developer and Product Creator. Aside from helping with the organisation of workshops and events, he is part of the strategic team and author of many of the blueprints.
  diana:
    name: Diana Knodel
    gplus: 117248579384664003770
    email: diana at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/diana.jpg
    about: has a background in computer science, psychology and educational research. She works as a Product Owner at XING and is engaged in the startup scence in Hamburg. She loves to share her enthusiasm about tech and coding as a volunteer at OpenTechSchool, always trying to get more girls and women into tech.
  duana:
    name: Duana Stanley
    gplus: 112209835624840039257
    email: duana at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/duana.jpg
    about: is Software Developer at Soundcloud and initiator of the Learners-meetup concept. As such she is organising this and other OpenTechSchool events.
  florian:
    name: Florian Gilcher
    gplus: 103019814974030696862
    email: florian at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/florian.jpg
    about: is a Software developer at asquera GmbH. He cofounded the Rust Hack and Learn and is also member of the global Rust community team.
  gio:
    name: Giorgia Sambrotta
    gplus: 112468997622326549149
    email: giorgia at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/giorgia.jpg
    about: is Web Designer at Delivery Hero. She is an active member behind the learners meetup format and organises OTS-Workshops on conferences and other external events.
  nicolai:
    name: Nicolai von Neudeck
    gplus: 113311475711898082984
    email: nicolai at OpenTechSchool dot org
    about: is a Data Recovery Engineer and Cultural Anthropologist. He initiated the opening hardware workshop, is very hands-on and helps where he can.
  philipp:
    name: Philipp Knodel
    gplus: 116233625155183238667
    email: phil at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/philipp.jpg
    about: has a background in political science focusing on international higher education policy. He stumbled into a Ruby on Rails course in San Francisco. And because there weren't many tech workshops for beginners in Hamburg he started the OpenTechSchool Hamburg.
  stefan:
    name: "Stefan Hoth"
    gplus: 111333123856542807695
    email: stefan at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/stefan.jpg
    about: is a freelance Web- and Mobile-Software Developer. Aside from being co-author and -host of the Android-Workshops, he helps with his huge network of contacts in the industry and works on the long-term strategy.
  steven:
    name: "Steven Farlie"
    gplus: 102640147012798270594
    email: steven at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/steven.jpg
    about: is a freelance Software Developer in Melbourne, Australia. After working with the Berlin OTS-Team and developing the great Social-Coding with Github-Workshop, he is now back in Australia to set up OTS there.
  rachel:
    name: Rachel Uwa
    gplus:
    email: rachel at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/rachel.jpg
    about: Organisation wizzard and keen on everything visual and design related, from 3D over visual effect up to interactive installation, she can talk with your for hours. As such she is leading the Design-, Processing and UI endevors of the OpenTechSchool Berlin.
  robert:
    name: "Robert Lehmann"
    gplus: 102202414125507005118
    email: robert at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/robert.jpg
    about: Robert is a systems engineer and Python coach.  He took OpenTechSchool from Berlin to Zurich, where he now works for Google.
  martin:
    name: "Martin Stadler"
    gplus:
    email: martin at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/martin.jpg
    about: Martin is a JavaScript app and web frontend developer from Berlin. At OpenTechSchool he co-organizes the Web Frontend Co-Learning and JavaScript workshops. He is also currently chair person of the OpenTechSchool foundation (e.V.).
  tobi:
    name: "Tobias Struckmeier"
    gplus: 111067385310263861440
    email: tobi at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/tobias.jpg
    about: Tobi is a software developer living in Dortmund, Germany. At OpenTechSchool he tries to help where possible and applicable. Working on PHP and JavasScript for food and fun.
  dennis:
    name: "Dennis Wilson"
    gplus: 
    email: dennis at OpenTechSchool dot org
    image: https://www.opentechschool.org/images/team/dennis.jpg
    about: Dennis is living in Dortmund, Germany. When he is not working on a freelance software developer, he co-organizes the OpenTechSchool Dortmund, does some open source and speaks at conferences.
default_author: aleks
# right now: OpenTechSchool Page, Aleks, Stefan, Amelie, Ben, Bea
fb_admins: "206143009512726,100004018402966,100000191404975,674380907,1443070876,100003987735511"

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : https://blog.opentechschool.org

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.2.13

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.com/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.com/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  #BASE_PATH : /

  # By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
  # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
  #
  # Override this by defining an absolute path to assets here.
  # ex: 
  #   http://s3.amazonaws.com/yoursite/themes/watermelon
  #   /assets
  #
  ASSET_PATH : false

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change theme here if needed.
  #
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  comments :
    provider : disqus
    disqus :
      short_name : opentechschool
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
   
  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #        
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-33344154-1'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'

  # Settings for sharing helper. 
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : false
    
  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.
  
prose:
 siteurl: "https://blog.opentechschool.org"
 media: "assets/content"
 metadata:
  _posts:
    - name: "categories"
      field:
        element: "hidden"
        value:
          - "post"
    - name: "layout"
      field:
        element: "hidden"
        value:
          - "post"
    - name: "author"
      field:
        element: "select"
        label: "Author"
        placeholder: "Select the Author"
        options:
          - name: "Aleks"
            value: "aleks"
          - name: "Beatrice"
            value: "bea"
          - name: "amelie"
            value: "Amélie"
          - name: "Angus"
            value: "angus"
          - name: "Ben"
            value: "ben"
          - name: "Diana"
            value: "diana"
          - name: "Duana"
            value: "duana"
          - name: "Giorgia"
            value: "gio"
          - name: "Nicolai"
            value: "nicolai"
          - name: "Stefan"
            value: "stefan"
          - name: "Steven"
            value: "steven"
          - name: "Rachel"
            value: "rachel"
          - name: "Robert"
            value: "robert"
          - name: "Tobi"
            vaue: "tobi"
        selected: "aleks"
